package com.example.shiftmanager;

import androidx.annotation.NonNull;

import com.google.firebase.firestore.FirebaseFirestore;
import com.google.firebase.firestore.QueryDocumentSnapshot;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Every Firestore read and write to do with people lives here, the same way
 * ShiftRepository owns everything to do with shifts.
 */
public class UserRepository {

    private final FirebaseFirestore db = FirebaseFirestore.getInstance();

    /** Everyone with the employee role, for the Staff Directory. */
    public void loadEmployees(@NonNull final Callback<List<AppUser>> callback) {
        db.collection(Constants.COLLECTION_USERS)
                .whereEqualTo(Constants.FIELD_ROLE, Constants.ROLE_EMPLOYEE)
                .get()
                .addOnSuccessListener(documents -> {
                    List<AppUser> employees = new ArrayList<>();
                    for (QueryDocumentSnapshot document : documents) {
                        employees.add(AppUser.fromDocument(document));
                    }
                    callback.onSuccess(employees);
                })
                .addOnFailureListener(callback::onError);
    }

    /** Reads one person, used to find out the signed-in user's display name and role. */
    public void loadUser(@NonNull String userId, @NonNull final Callback<AppUser> callback) {
        db.collection(Constants.COLLECTION_USERS)
                .document(userId)
                .get()
                .addOnSuccessListener(document -> {
                    if (!document.exists()) {
                        callback.onError(new IllegalStateException("No profile for this user"));
                        return;
                    }
                    callback.onSuccess(AppUser.fromDocument(document));
                })
                .addOnFailureListener(callback::onError);
    }

    /**
     * Adds an employee the manager typed in by hand.
     *
     * This person has no login yet, so the document id is generated by Firestore rather
     * than being an auth uid. When they later sign in for the first time, LoginActivity
     * creates their own document keyed by uid. The directory is therefore a roster of the
     * business, not strictly a list of accounts -- which matches how HW2 described it
     * ("the total pool of staff available for shifts").
     */
    public void addEmployee(@NonNull String name, @NonNull String email,
                            @NonNull final Callback<String> callback) {
        Map<String, Object> data = new HashMap<>();
        data.put(Constants.FIELD_NAME, name);
        data.put(Constants.FIELD_EMAIL, email);
        data.put(Constants.FIELD_ROLE, Constants.ROLE_EMPLOYEE);
        data.put(Constants.FIELD_ACTIVE, true);
        data.put(Constants.FIELD_CREATED_AT, System.currentTimeMillis());

        db.collection(Constants.COLLECTION_USERS)
                .add(data)
                .addOnSuccessListener(reference -> callback.onSuccess(reference.getId()))
                .addOnFailureListener(callback::onError);
    }

    /**
     * Removes an employee from the business, along with any shift they had applied for.
     *
     * Leaving their registrations behind would keep them counted against a shift's
     * capacity and would show their name on the approval screen after they were gone.
     */
    public void removeEmployee(@NonNull final String employeeId,
                               @NonNull final Callback<Void> callback) {
        db.collection(Constants.COLLECTION_REGISTRATIONS)
                .whereEqualTo(Constants.FIELD_EMPLOYEE_ID, employeeId)
                .get()
                .addOnSuccessListener(registrations -> {
                    for (QueryDocumentSnapshot registration : registrations) {
                        registration.getReference().delete();
                    }
                    db.collection(Constants.COLLECTION_USERS)
                            .document(employeeId)
                            .delete()
                            .addOnSuccessListener(callback::onSuccess)
                            .addOnFailureListener(callback::onError);
                })
                .addOnFailureListener(callback::onError);
    }
}
